steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/$PROJECT_ID/tsunami-repo/tsunami-scanner:latest',
    '-f',
    'cloud.Dockerfile',
    '.'
  ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/tsunami-repo/tsunami-scanner:latest'
